### ISSUE TITLE
PacketProxyLib.jar以外の依存関係を含んだプラグインが動作しない

### ISSUE THREAD

**Issue by prprhyt** [DeNA/PacketProxyPlugin#1]
プラグインにPacketProxyLib.jarに含まれていない依存関係があると
PacketProxyからパッケージを参照できないため
Servers->Addボタンを押した時に
`Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError:`
が発生してエンコードを設定するダイアログが表示されない。

**Comment by funa-tk** [comment]
マージ済み
